"""Health Monitoring — manual vitals tracking, trends and AI insights.

Supports: weight, height, BMI, blood pressure, sugar level, heart rate,
blood oxygen, temperature, sleep hours, water intake, daily steps and mood.

BMI is computed on the fly from the latest height and weight entries.
AI insights are generated by Nemotron through the shared AI service and
degrade to a rule-based fallback when AI is unavailable.
"""

import json
import logging
from datetime import datetime, timedelta
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

from core.security import get_current_user, resolve_target_user_id
from core.time_utils import day_bounds, now_local, today_local
from database import get_db
from models import HealthMetric, User
from services.ai_config import TASK_ASSISTANT, is_configured
from services.ai_service import ai_service

logger = logging.getLogger("pillsync-health")

router = APIRouter(prefix="/health", tags=["Health Monitor"])

VALID_METRICS = (
    "weight",
    "height",
    "bmi",
    "blood_pressure",
    "sugar_level",
    "heart_rate",
    "blood_oxygen",
    "temperature",
    "sleep_hours",
    "water_intake",
    "daily_steps",
    "mood",
)

METRIC_LABELS = {
    "weight": "Weight",
    "height": "Height",
    "bmi": "BMI",
    "blood_pressure": "Blood Pressure",
    "sugar_level": "Sugar Level",
    "heart_rate": "Heart Rate",
    "blood_oxygen": "Blood Oxygen",
    "temperature": "Temperature",
    "sleep_hours": "Sleep",
    "water_intake": "Water Intake",
    "daily_steps": "Daily Steps",
    "mood": "Mood",
}

METRIC_UNITS = {
    "weight": "kg",
    "height": "cm",
    "bmi": "",
    "blood_pressure": "mmHg",
    "sugar_level": "mg/dL",
    "heart_rate": "bpm",
    "blood_oxygen": "%",
    "temperature": "°C",
    "sleep_hours": "hrs",
    "water_intake": "ml",
    "daily_steps": "steps",
    "mood": "/5",
}


class HealthMetricIn(BaseModel):
    metric_type: str = Field(..., min_length=1, max_length=40)
    value: float = Field(..., ge=-9999, le=99999)
    value_text: str = ""
    unit: str = ""
    notes: str = ""
    recorded_at: Optional[str] = None


def _normalize_type(metric_type: str) -> str:
    cleaned = (metric_type or "").strip().lower().replace(" ", "_")
    if cleaned in VALID_METRICS:
        return cleaned
    return "other"


def _metric_dict(record: HealthMetric) -> dict:
    return {
        "id": record.id,
        "metric_type": record.metric_type,
        "label": METRIC_LABELS.get(record.metric_type, record.metric_type.title()),
        "value": record.value,
        "value_text": record.value_text or "",
        "unit": record.unit or METRIC_UNITS.get(record.metric_type, ""),
        "notes": record.notes or "",
        "recorded_at": record.recorded_at.isoformat() if record.recorded_at else None,
    }


def _compute_bmi(db: Session, user_id: int) -> Optional[dict]:
    weight = (
        db.query(HealthMetric)
        .filter(HealthMetric.user_id == user_id, HealthMetric.metric_type == "weight")
        .order_by(HealthMetric.recorded_at.desc())
        .first()
    )
    height = (
        db.query(HealthMetric)
        .filter(HealthMetric.user_id == user_id, HealthMetric.metric_type == "height")
        .order_by(HealthMetric.recorded_at.desc())
        .first()
    )
    if not weight or not height or height.value <= 0:
        return None
    bmi = round(weight.value / ((height.value / 100) ** 2), 1)
    if bmi < 18.5:
        band = "Underweight"
    elif bmi < 25:
        band = "Normal"
    elif bmi < 30:
        band = "Overweight"
    else:
        band = "Obese"
    return {
        "value": bmi,
        "unit": "",
        "band": band,
        "weight_kg": weight.value,
        "height_cm": height.value,
        "recorded_at": weight.recorded_at.isoformat() if weight.recorded_at else None,
    }


def _parse_pressure(text: str) -> dict:
    if not text:
        return {}
    parts = str(text).replace(",", "/").split("/")
    try:
        return {"systolic": float(parts[0]), "diastolic": float(parts[1])}
    except (ValueError, IndexError):
        return {}


@router.post("/metrics", status_code=201)
def create_metric(
    data: HealthMetricIn,
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    metric_type = _normalize_type(data.metric_type)
    recorded_at = None
    if data.recorded_at:
        try:
            recorded_at = datetime.fromisoformat(data.recorded_at)
        except ValueError:
            recorded_at = None
    record = HealthMetric(
        user_id=user.id,
        metric_type=metric_type,
        value=data.value,
        value_text=data.value_text,
        unit=data.unit or METRIC_UNITS.get(metric_type, ""),
        notes=data.notes,
        recorded_at=recorded_at or now_local().replace(tzinfo=None),
    )
    db.add(record)
    db.commit()
    db.refresh(record)
    return _metric_dict(record)


@router.get("/metrics")
def list_metrics(
    metric: Optional[str] = Query(None, alias="metric_type"),
    days: int = Query(30, ge=1, le=365),
    limit: int = Query(100, ge=1, le=500),
    patient_id: Optional[int] = Query(None),
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    target_id = resolve_target_user_id(db, user, patient_id)
    query = db.query(HealthMetric).filter(HealthMetric.user_id == target_id)
    if metric:
        query = query.filter(HealthMetric.metric_type == _normalize_type(metric))
    cutoff = now_local().replace(tzinfo=None) - timedelta(days=days)
    query = query.filter(HealthMetric.recorded_at >= cutoff)
    records = query.order_by(HealthMetric.recorded_at.desc()).limit(limit).all()
    return {
        "metrics": [_metric_dict(r) for r in records],
        "count": len(records),
        "valid_types": list(VALID_METRICS),
        "units": METRIC_UNITS,
        "labels": METRIC_LABELS,
    }


@router.delete("/metrics/{metric_id}")
def delete_metric(
    metric_id: int,
    patient_id: Optional[int] = Query(None),
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    target_id = resolve_target_user_id(db, user, patient_id)
    record = (
        db.query(HealthMetric)
        .filter(HealthMetric.id == metric_id, HealthMetric.user_id == target_id)
        .first()
    )
    if not record:
        raise HTTPException(status_code=404, detail="Metric not found")
    db.delete(record)
    db.commit()
    return {"message": "Metric deleted"}


@router.get("/summary")
def health_summary(
    days: int = Query(30, ge=1, le=365),
    patient_id: Optional[int] = Query(None),
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    target_id = resolve_target_user_id(db, user, patient_id)
    cutoff = now_local().replace(tzinfo=None) - timedelta(days=days)
    records = (
        db.query(HealthMetric)
        .filter(HealthMetric.user_id == target_id, HealthMetric.recorded_at >= cutoff)
        .order_by(HealthMetric.recorded_at.asc())
        .all()
    )

    latest: dict[str, dict] = {}
    trends: dict[str, list] = {}
    for record in records:
        key = record.metric_type
        latest[key] = _metric_dict(record)
        trends.setdefault(key, []).append(_metric_dict(record))

    return {
        "latest": latest,
        "bmi": _compute_bmi(db, target_id),
        "trends": trends,
        "count": len(records),
        "days": days,
    }


@router.get("/trends")
def health_trends(
    metric_type: str = Query("weight"),
    days: int = Query(14, ge=2, le=365),
    patient_id: Optional[int] = Query(None),
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    target_id = resolve_target_user_id(db, user, patient_id)
    metric = _normalize_type(metric_type)
    cutoff = now_local().replace(tzinfo=None) - timedelta(days=days)
    records = (
        db.query(HealthMetric)
        .filter(
            HealthMetric.user_id == target_id,
            HealthMetric.metric_type == metric,
            HealthMetric.recorded_at >= cutoff,
        )
        .order_by(HealthMetric.recorded_at.asc())
        .all()
    )

    values = [_metric_dict(r) for r in records]
    change = None
    if len(values) >= 2:
        change = round(values[-1]["value"] - values[0]["value"], 2)

    return {
        "metric_type": metric,
        "label": METRIC_LABELS.get(metric, metric.title()),
        "unit": METRIC_UNITS.get(metric, ""),
        "values": values,
        "change": change,
        "count": len(values),
    }


@router.get("/insights")
def health_insights(
    days: int = Query(14, ge=1, le=90),
    patient_id: Optional[int] = Query(None),
    user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    target_id = resolve_target_user_id(db, user, patient_id)
    data = health_summary(days=days, patient_id=patient_id, user=user, db=db)

    summary = {
        "user_name": user.name,
        "bmi": data["bmi"],
        "latest": {
            key: {"value": v["value"], "value_text": v["value_text"], "unit": v["unit"]}
            for key, v in data["latest"].items()
        },
    }
    for key in ("weight", "heart_rate", "sugar_level", "blood_pressure", "sleep_hours", "daily_steps"):
        if key in data["trends"]:
            trend = data["trends"][key]
            if len(trend) >= 2:
                summary.setdefault("trends", {})[key] = {
                    "first": trend[0]["value"],
                    "last": trend[-1]["value"],
                    "change": round(trend[-1]["value"] - trend[0]["value"], 2),
                }

    ai_text = None
    engine = "rule-based"
    try:
        ai_text = ai_service.lifestyle_advice(
            "You are the PillSync health analytics assistant. Based ONLY on the user's "
            "health metrics JSON below, write a short, non-diagnostic wellness review "
            "with three markdown sections: Observations, What To Watch, and Suggestions. "
            "Keep it under 200 words. Flag anything outside typical healthy ranges "
            "gently and always advise consulting a clinician. Do not diagnose.\n"
            f"Data:\n{json.dumps(summary, ensure_ascii=False, default=str)}"
        )
    except Exception as exc:  # never break the health page
        logger.info("AI health insights unavailable: %s", exc.__class__.__name__)

    if ai_text:
        engine = "ai"
    else:
        lines = ["## Observations", ""]
        latest = summary.get("latest", {})
        if latest.get("heart_rate"):
            hr = latest["heart_rate"]["value"]
            lines.append(f"- Latest heart rate is **{hr} bpm**." if 60 <= hr <= 100 else f"- Heart rate reads **{hr} bpm** — worth discussing with your clinician.")
        if latest.get("sleep_hours"):
            sleep = latest["sleep_hours"]["value"]
            lines.append(f"- You logged **{sleep} hours** of sleep most recently." if sleep >= 7 else f"- Sleep is around **{sleep} hours** — aim for 7–9 hours where possible.")
        if latest.get("water_intake"):
            water = latest["water_intake"]["value"]
            lines.append(f"- Water intake logged at **{water} ml**.")
        if summary.get("bmi"):
            lines.append(f"- Your BMI is **{summary['bmi']['value']}** ({summary['bmi']['band']}).")
        if not lines[1:]:
            lines.append("- Start logging a few metrics daily and insights will appear here.")
        lines += ["", "## What To Watch", ""]
        lines += [
            "- Consistent daily logging gives the most useful trends.",
            "- Sudden jumps in heart rate, sugar, or blood pressure deserve a clinician check.",
        ]
        lines += ["", "## Suggestions", ""]
        lines += [
            "- Log your vitals at roughly the same time each day.",
            "- Pair health tracking with your medication routine.",
            "- Review these trends with your doctor at your next visit.",
        ]
        ai_text = "\n".join(lines)

    return {
        "insights": ai_text,
        "engine": engine,
        "ai_configured": is_configured(),
        "summary": data,
    }